# Generated by Django 5.2.8 on 2025-11-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
